#!/bin/bash

db_user=mycryptochat
db_name=mycryptochat
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting mycryptochat domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/mycryptochat
sudo rm -f /etc/nginx/conf.d/$domain.d/mycryptochat.conf

sudo service nginx reload
